<a href="https://colab.research.google.com/github/mfernandes10/MetNumUN2023I/blob/main/Quiz1/mfernandes_Quiz1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [59]:
!python --version
import numpy as np

print('NumPy', np.__version__)

Python 3.8.10
NumPy 1.22.4


## **1. *FizzBuzz*  - Python**

---

###**Problem Description**

**Task:** Given an integer $x$ return:
 

*   The string "**`Fizz!`**" if $x$ is divisible by $3$ and not  divisible by $5$.
*    The string "**`Buzz!`**" if $x$ is divisible by $5$ and not  divisible by $3$.
*    The string "**`FizzBuzz!`**" if $x$ is divisible by both $5$ and divisible by $3$.
*    The string "**`...`**" otherwise.

**Input Format:** The input consists of a single integer $x$. 

**Constraints:** $x$ is an integer

**Output Format:**  the output is a string.

**Solution**

In [60]:
#Do not change this function's name, parameters or output format. It will be used in automatic grading.
answer = " " 
def FizzBuzz(x):
  if (x % 3==0) and not (x % 5 == 0):
    return "Fizz!"
  elif (x % 5==0) and not (x % 3==0):
      return "Buzz!"
  elif (x % 3==0) and (x % 5==0):
        return "FizzBuzz!"
  else: 
          return "..."


<details>    
<summary>
    <font size="3" color="darkgreen"><b>Verification cases </b></font>
</summary>


In [61]:
print(FizzBuzz(3))
print(FizzBuzz(7))
print(FizzBuzz(5))
print(FizzBuzz(11))
print(FizzBuzz(15))

Fizz!
...
Buzz!
...
FizzBuzz!


Expected output:
``` 
Fizz!
...
Buzz!
...
FizzBuzz!
```

## **2. *FizzBuzzList*  - Python**
---

Write the function *FizzBuzzList* that returns a list with the answers of *FizzBuzz* for the integer numbers $1$ to $n$ (including $n$).

---

###**Problem Description**

**Task:** Given an integer $n$ return the list with the *FizzBuzz* answers for the integer numbers $1$ to $n$ (including $n$).
  

**Input Format:** The input consists of a single integer $n$. 

**Constraints:** $n$ is an integer

**Output Format:**  list with the *FizzBuzz* answers, if the input is not positive return an empty list.

**Solution**

In [62]:
#Do not change this function's name, parameters or output format. It will be used in automatic grading.
def FizzBuzzList(n):
    ans = []
    for i in range(n):
      ans.append(FizzBuzz(i+1))
    return ans

<details>    
<summary>
    <font size="3" color="darkgreen"><b>Verification cases </b></font>
</summary>

In [63]:
print(FizzBuzzList(5))
print(FizzBuzzList(-30))

['...', '...', 'Fizz!', '...', 'Buzz!']
[]


Expected output:
``` 
['...', '...', 'Fizz!', '...', 'Buzz!']
[]
```

## **3. *Standarize* - z scores - NumPy**

**IMPORTANT:** Solve this exercise using the ***`NumPy`*** functions ***`mean`*** and ***`std`*** not using prograrmming structures like ***`if`*** or ***`for`***.

In [64]:
import numpy as np

X = np.array([1.2,3.2,4.3,5.6])
print(X.mean())
print(X.std())

3.5749999999999997
1.6130328576938535


---

###**Problem Description**

**Task:** Given an numpy array $X$ return the corresponding standard scores.
  
**Input Format:** The input consists of a numpy array $X$. 

**Output Format:**  A numpy array with standard scores corresponding to $X$.

**Solution**

In [65]:
#Do not change this function's name, parameters or output format. It will be used in automatic grading.

import numpy as np

def standarize(X):
  X_standarized = (X-X.mean())/X.std() # only one line of code
  return X_standarized

## **4. *Main diagonal matrix*  - NumPy**

In [66]:
#t = [array([], dtype=float64), array([nan]), array([-1.,  1.]), array([-1.22474487,  0.        ,  1.22474487]), array([-1.34164079, -0.4472136 ,  0.4472136 ,  1.34164079]), array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356]), array([-1.46385011, -0.87831007, -0.29277002,  0.29277002,  0.87831007,
  #      1.46385011]), array([-1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5]), array([-1.52752523, -1.09108945, -0.65465367, -0.21821789,  0.21821789,
   #     0.65465367,  1.09108945,  1.52752523]), array([-1.54919334, -1.161895  , -0.77459667, -0.38729833,  0.        ,
    #    0.38729833,  0.77459667,  1.161895  ,  1.54919334])]

**IMPORTANT:** Solve this exercise using the ***`NumPy`*** function ***`diag`***  and ***`astype`*** not using prograrmming structures like ***`if`*** or ***`for`***.

In [67]:
import numpy as np
A = np.array([
    [1, 0, 2, 9, 2],
    [9, 2, 6, 5, 7],
    [6, 4, 3, 4, 7]
    
])

print(A.astype(float))

print(np.diag(A))

print(np.diag(np.diag(A)))

[[1. 0. 2. 9. 2.]
 [9. 2. 6. 5. 7.]
 [6. 4. 3. 4. 7.]]
[1 2 3]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


---

###**Problem Description**

**Task:** Given a numpy matrix $A$ (2-D array) return the diagonal matrix with the elements of its main diagonal.
 

**Input Format:** The input consists of a numpy matrix $A$ (2-D array).

**Output Format:**  The diagonal matrix with the elemnts of its main diagonal.

In [68]:
#Do not change this function's name, parameters or output format. It will be used in automatic grading.

import numpy as np

def main_diagonal_matrix(A):
  D = np.diag(np.diag(A)).astype(float) # only one line of code
  return D